#! /bin/sh

sxhkd &


rm -r ~/Downloads
rm -r ~/Desktop

setxkbmap -layout es

external_monitor=$(xrandr --query | grep 'HDMI2')
if [[ $external_monitor = *connected* ]]; then
    xrandr --output HDMI2 --primary --auto --output eDP1 --auto --right-of HDMI2
    bspc monitor HDMI2 -d I II III IV V
    bspc monitor eDP1 -d VI VII VII IX X
else
    bspc monitor -d I II III IV V VI VII VII IX X
fi

~/.config/polybar/launch.sh

bspc config border_width         0
bspc config window_gap          3

bspc config split_ratio          0.5
bspc config borderless_monocle   true
bspc config gapless_monocle      true
bspc config leaf_monocle	 true

bspc rule -a urxvt state=floating
bspc rule -a URxvt state=floating

xrdb -merge ~/.Xresources
feh --bg-scale /home/andrew/.config/wallpapers/pier.jpg
picom --experimental-backends
