#! /bin/sh

sxhkd &

~/.config/polybar/launch.sh

rm -r ~/Downloads
rm -r ~/Desktop

setxkbmap -layout es

bspc monitor -d I II III IV V VI VII VIII IX X

bspc config border_width         1
bspc config window_gap          3

bspc config split_ratio          0.5
bspc config borderless_monocle   true
bspc config gapless_monocle      true

bspc rule -a urxvt state=floating
bspc rule -a URxvt state=floating

xrdb -merge ~/.Xresources
feh --bg-scale /home/andrew/.config/wallpapers/pier.jpg
picom --experimental-backends
